- README.md
- cmd/tdexd/main_test.go
- config/config.go
- go.mod
- go.sum
- pkg/wallet/blind.go
This updates the version of go elements to the latest v0.1.1 which fixes problems with the verification of the surjection proofs.
> Move to go-elements v0.1.1 & minor fixes

- README.md
This updates the readme to be up to date with the current Makefile targets
> Update development commands in README

- cmd/tdex/initwallet.go
> Add --restore flag to init command

- cmd/tdexd/main.go
> market fee config bug fix

- .goreleaser.yml
- Dockerfile
- go.mod
- go.sum
- pkg/explorer/go.sum
[goreleaser] add --build-arg to docker build step
> docker build args

- go.mod
- go.sum
- internal/core/application/operator_service.go
- internal/core/application/wallet_service.go
- internal/interfaces/grpc/handler/operator.go
This adds ReloadtUtxos RPC implementation which can be used to reload unspents from blockchain.
This closes #299 
> Rpc reload utxos

- go.mod
- go.sum
- internal/core/application/operator_service.go
- internal/core/application/types.go
- internal/core/domain/market_repository.go
- internal/infrastructure/storage/db/badger/market_repository_impl.go
- internal/infrastructure/storage/db/inmemory/market_memory_repository_impl.go
- internal/interfaces/grpc/handler/operator.go
This adds DropMarket RPC implementation and ListMarket update.
This closes #246 
This closes #281 
> DropMarket impl, ListMarket update

- cmd/tdex/listutxos.go
- cmd/tdex/main.go
- cmd/tdex/reloadutxos.go
This adds listutxos and reloadutxos commands.
> listutxos and reloadutxos cli added

- pkg/wallet/blind.go
> Hotfix: prevent panicking when blinding a trade tx

- internal/core/application/trade_service.go
> Increase verbosity of FillProposal

- internal/core/application/trade_service.go
- pkg/wallet/blind.go
Before this, `ExtractBlindingDataFromTx` and `BlindSwapTransactionWithData` were respectively returning and expecting inputs' blinding data grouped by their prevout script. In case of swaps like this where multiple inputs have the same prevout script, this kind of handling causes the transaction to be wrongly blinded because all those inputs would have the same blinding data instead of one each.
WIth this inputs' blinding data are grouped by input index to fix the described bug.
Also, in fillProposal the eventual error raised when signing a tx were nor checked nor returned. This adds the missing err check block.
> Fix transaction blinding & raise error if signing fails

- .goreleaser.yml
> Include extra files in go release

- internal/interfaces/grpc/handler/trade.go
> Return fixed fee in Balances RPC reply

- internal/core/domain/trade_model.go
This prevents the swapParser.SerializeComplete method to try finalize and extract the final tx in case the one provided is already an hex string.
> Hotfix trade complete with tx hex

- internal/core/application/trade_service_test.go
- internal/infrastructure/storage/db/badger/db_manager.go
This fixes race issue within tests.
This closes #420 
> fix race test issue

- cmd/unlockerd/main.go
This adds a new flag `--insecure` to the unlocker service in order to prevent it from sourcing the TLS certificate from the selected provider.
This closes #427.
Please @tiero review this.
> [Unlocker] Add --insecure flag 

- internal/interfaces/grpc/http_utils.go
- internal/interfaces/grpc/service.go
This updates the creation of the multiplexer with grpc server, http2 grpc-web server and http1 grpc-web server.
This also fixes the signing algorithms supported in TLS configuration.
This closes #415.
This closes #418.
> Refactor serveMux

- internal/interfaces/grpc/handler/operator.go
This fixes the validation of the price in the request of UpdateMarketPrice at interface level.
> HotFix: price validation in gRPC handler

- internal/core/application/blockchain_listener.go
- internal/core/application/pubsub_utils.go
> Add event info to payloads of webhook service

- config/config.go
> [Config] Unset base asset if quote is fixed

- internal/core/application/operator_service.go
> Use fee account for marketfragmenter withdrawals

- internal/core/application/operator_service.go
This adds a new check in the market fragmentation flow ensuring that the amount to fragment is at least 100K sats regardless of the asset type. 
Closes #527.
> [MarketFragmenter] Check for small amounts

- internal/core/application/operator_service.go
> Allow to withdraw all LBTC funds from Fee account

- cmd/tdex/market.go
- go.mod
- go.sum
- internal/interfaces/grpc/handler/operator.go
- internal/interfaces/grpc/handler/trade.go
This fixes rounding issue caused by float64-float32 conversion of price.
This closes #550 
> price type update

- cmd/tdexd/main.go
- config/config.go
- internal/interfaces/grpc/service.go
This adds unlocking wallet on startup if wallet unlock password file is provided through env var.
This closes #557 
> Unlock wallet on startup

- internal/interfaces/grpc/handler/transport.go
> Support content-type JSON

- cmd/tdexd/main.go
- config/config.go
- internal/interfaces/grpc/service_one_port.go
This adds option to run trade and operator services on same port if defined by config.
This closes #613 
> Run operator and trade services on same port

- internal/interfaces/grpc/service.go
- internal/interfaces/grpc/service_one_port.go
> Fix register transport handler

- internal/interfaces/grpc/http_utils.go
> Allow pre-flight requests

- internal/interfaces/grpc/http_utils.go
- internal/interfaces/http/tdex_connect_handler.go
This adds CORS headers to HTTP responses.
This closes #638 
> Add CORS headers to http responses

- internal/interfaces/grpc/service.go
This removes panic that was happening as reported in issue #612 
This closes #612 
> InitWallet panic bug

- cmd/tdex/config.go
- cmd/tdex/main.go
- internal/interfaces/http/tdex_connect_handler.go
- pkg/tdexdconnect/tdexdconnect.go
This sets no_tls flag to true if proto=http.
This closes #643 
> tdexconnect support proto=http

- internal/interfaces/grpc/handler/walletunlocker.go
This checks if macaroon file is empty in InitWallet RPC call and retries reading from file until populated.
This closes #646 
> Macaroon not empty check - InitWallet

- web/layout.html
It closes #656 
Trader endpoint tab has been disabled for now, just need to remove a line (see TODO).
Please review @tiero
> Choose endpoints with tabs + QR code
