tdex-network/tdex-daemon

- Makefile
- cmd/tdexd/main.go
- internal/core/application/blockchain_listener.go
- internal/core/application/test_util.go
- internal/core/application/wallet_service.go
- internal/core/domain/vault_model.go
- pkg/crawler/service.go
Before this, the bc listener was started by the main function of the daemon. This was the cause of annoying  warn messages when restoring an already used wallet. With this, the bc listener and crawler services are activated only after unlocking the wallet.
Also prior this, there was a bug that was not allowing the operator to unlock a restored wallet. This addresses the issue by setting the plain text mnemonic to viper within the `NewVault` factory function of the vault domain.
Last but not least, this makes sure that after the wallet is initialized, it's locked no matter if an error in the meanwhile.
This closes #226 
This closes #185.
> Start observing blockchain after unlock

- cmd/tdex/config.go
This PR fix typo mistake "base asset..." to "quote asset..."
@tiero
> Fix typo for error msg in config.go

- pkg/crawler/observable.go
- pkg/httputil/httputil.go
This decrease http client timeout and fix crawler issue which was happening when explorer returns error.
> decrease http client timeout & crawler return when error

- cmd/tdexd/main.go
- config/config.go
- go.mod
- go.sum
- pkg/stats/stats.go
This adds basic instrumentation, it prints basic process info like memory allocation and a number of goroutines.
On server stop event all default prometheus stats are printed to a file, this can potentially help to see basic info before server is stopped.
@tiero @altafan please review if you think that this can be usefull.
> basic instrumentation added

- go.mod
- go.sum
- internal/infrastructure/storage/db/badger/db_manager.go
- internal/infrastructure/storage/db/badger/trade_repository_impl.go
- internal/infrastructure/storage/db/badger/unspent_repository_impl.go
This fixes #249:
* Add garbage collection
* Change binary serialization instead of JSON
* Tweaks badger configuration to avoid memory-mapping log files.
Moving to binary serialization drastically improves memory usage.
I tried to run 3 different daemons with the same configuration and by repeating the same operations:
* derive 5 fee addresses and fund each of them with 10 utxos (50 in total)
* derive 5 addresses for a market and fund the market with 1 utxo per each address
The first daemon was the master version and the datadir, overall, ended occupying 4.7MB on disk.
The second daemon had all the changes but the binary serialization and its datadir was 3.7MB.
The last daemon had all the changes and took only 315KB on the disk.
> Optimize memory compsumption

- .goreleaser.yml
- Makefile
- scripts/build
- scripts/build-cli
This is just an improvement for build scripts, to automatically recognize OS and ARCH for the build. Cross-compilation takes place on CI via .goreleaser.yml﻿ so no need to custom scripts 
Please @altafan review
> Update Makefile targets and build scripts

- pkg/crawler/service_test.go
- pkg/explorer/block.go
- pkg/explorer/explorer.go
This adds new method, GetBlockHeight, to the explorer package.
It returns block tip of the blockchain.
> get block height

- cmd/tdexd/main.go
- internal/core/application/blockchain_listener.go
- internal/core/application/operator_service.go
- internal/core/application/test_util.go
- internal/core/application/trade_service.go
- internal/core/application/wallet_service.go
- pkg/crawler/crawler.go
- pkg/crawler/event.go
- pkg/crawler/observable.go
- pkg/crawler/service.go
- pkg/crawler/service_test.go
This contains a little refactor of the crawler pkg and also of the BlockchainListener service of the application level.
Before this, the crawler was using a single ticker for all its observables, now, on the contrary, every observable has its own ticker (every ticker has the same duration still - refers to CRAWL_INTERVAL env var).
The usage of its inner channels has been fixed:
* the original `quitChan` has been removed
* `errChan` is closed when stopping the crawler
* a special event `QuitEvent` is now sent over the `eventChan` to notify the client (listening for events with `GetEventChannel()`) that no more events will be sent over the channel, which can be considered closed. In fact, this happens ONLY when stopping the crawler. Since the crawler manages many go-routines (one per each …
> Crawler and BlockchainListener improvements

- go.mod
- go.sum
- internal/core/application/wallet_service.go
- internal/core/application/wallet_service_test.go
- internal/interfaces/grpc/handler/wallet.go
Before this, the daemon was always trying to restore the wallet while processing an `InitWallet` request. This has been made optional now. The operator can specify if the wallet must be restore by adding a `restore: true` flag to the request. By default the restoration is skipped.
Closes #264.
Please @tiero review this
> Optional restore for InitWallet

- internal/core/application/blockchain_listener.go
Correcting a typo in the method name `listenToEventChannel`﻿
> [Typo] listenToEventChannel instead of listen-t-ToEventChannel

- pkg/explorer/elements/service.go
- pkg/explorer/elements/transaction.go
- pkg/explorer/elements/unspents.go
This fixes the Elements explorer so that addresses are rescanned only when restoring funds (GetTransactionsForAddress), preventing do so when fetching unspents for address(es) (GetUnspents GetUnspentsForAddresses).
Please @tiero review this
> [Elements explorer] Rescan only when restoring funds

- .goreleaser.yml
This is a small change that imporove the automatic release pipeline:
* Do not push docker tag latest if the pushed﻿ git tag is not stable (ie. something like v1.0.0-rc.1 or v1.0.0-alpha.1 etc..)
* If the git tag is not stable, the Github Release will have a Pre-Release flag
> skip docker push of latest tag if pre-release

- config/config.go
- internal/core/application/wallet_service.go
- pkg/crawler/observable.go
- pkg/crawler/service_test.go
- pkg/explorer/elements/service.go
- pkg/explorer/elements/transaction.go
- pkg/explorer/elements/transaction_test.go
- pkg/explorer/elements/unspents.go
- pkg/explorer/esplora/transaction.go
- pkg/explorer/esplora/transaction_test.go
- pkg/explorer/esplora/unspents_test.go
- pkg/explorer/explorer.go
CHANGELOG:
* Add a `blindKey` arg to the explorer interface's GetTransansactionsForAddress and relative changes. 
* Disable restore wallet with Elements explorer.
* Improve crawler logs by logging only start/stop of an observable.
Closes #283.
Closes #282.
> Disable restore wallet with Elements

- config/config.go
This increases the crawler default interval from 2 to 5 secs.
> Increase crawler default interval

- internal/core/application/blockchain_listener.go
Adding this microsecond of sleep in `listenToEventChannel` loop in `blockchain_listener` prevents the loop to eat all the CPU.
This may be the reason of this https://github.com/TDex-network/tdex-daemon/issues/287
Not closing yet until we have "numbers"
> microsecond sleep to preven high CPU usage

- internal/core/domain/vault_model.go
This fixes bug caused by wrong Vault initialisation which was missing network. 
> Pass network in Vault initialisation

- cmd/tdex/claimfee.go
- cmd/tdex/claimmarket.go
- cmd/tdex/dropmarket.go
- cmd/tdex/main.go
This adds the `claimfee`, `claimmarket` and `dropmarket` commands to the CLI.
> Add CLI commands for claiming deposit & claiming fee RPCs

- internal/core/application/trade_service.go
This reintroduces the log of the hex of a trade tx in case it fails to be included in mempool when broadcasted via the explorer service.
> Add txhex log in case of broadcast failing

- internal/core/application/operator_service.go
- internal/core/application/trade_service_test.go
- internal/core/application/wallet_service.go
- internal/core/domain/unspent_model.go
- internal/core/domain/unspent_service.go
- internal/infrastructure/storage/db/test/unspent_repository_impl_test.go
The last commit introduced a bug in the trade flow, and traders using the mobile app were experiencing an issue when the completing a swap. With that commit, the daemon didn't store range and surjection proofs of unspents anymore, causing the upset inputs of the swaps to have null proofs. This is likely to be the cause of the bug. The app, which uses liquidjs, is able to deserialize empty proofs, but it doesn't properly encode them in case they're empty.
This addresses the problem by restoring the proofs in the unspent domain, but keeping them always zeroed ([0x00]), as it's done in the Elements protocol for an output nonce when the output itself is uncofnidential: the nonce is zeroed, that means it contains a single 0 byte, instead of being null.
I made sure that go and js clients are …
> Hotfix: Restore proofs

- cmd/tdex/main.go
This lets the user of the CLI to define its datadir by setting the env variable `TDEX_OPERATOR_DATADIR`. If not set it defaults to the usual appdata/tdex-operator.
> Let the operator to configure CLI datadir

- internal/core/application/trade_service.go
- internal/core/domain/trade_model.go
- internal/core/domain/trade_service.go
- internal/core/domain/trade_service_test.go
- pkg/swap/complete.go
- pkg/swap/complete_test.go
- pkg/trade/buy.go
This adds some little changes in order to allow the daemon to receive not just psets in base64 format, but also already extracted raw txs in hex format.
> Allow receiving tx hexes in TradeComplete RPC

- internal/core/application/errors.go
- internal/core/application/trade_service.go
- internal/core/application/types.go
This adds a generic error `service is unavailable, retry later` that is returned by the trade service in case of internal errors. The internal errors are logged rather than being forwarded to the user who made the request.
This closes #344.
> General error in trade service & add balances to GetMarketPrice application method

- internal/core/application/operator_service.go
- internal/core/application/trade_service.go
- internal/core/application/trade_service_test.go
- internal/core/application/types.go
- internal/core/application/wallet_service.go
- internal/core/domain/market_model.go
- internal/core/domain/market_model_test.go
- internal/core/domain/market_service.go
- internal/core/domain/market_service_test.go
- internal/core/domain/trade_service.go
- internal/core/domain/trade_service_test.go
- internal/infrastructure/storage/db/badger/market_repository_impl.go
- internal/infrastructure/storage/db/inmemory/market_memory_repository_impl.go
- internal/infrastructure/storage/db/test/market_repository_impl_test.go
- internal/interfaces/grpc/handler/operator.go
This makes the previous changes to the market fees backward compatible with previous versions of the daemon.
Plus, this moves the lock of the unspents of an accepted trade outside the go routine.
> Market fees backward compatibility

- internal/core/application/mocks_test.go
- pkg/crawler/service_test.go
- pkg/explorer/elements/transaction.go
- pkg/explorer/elements/transaction_test.go
- pkg/explorer/elements/unspents_test.go
- pkg/explorer/esplora/transaction.go
- pkg/explorer/esplora/transaction_test.go
- pkg/explorer/esplora/unspents_test.go
- pkg/explorer/explorer.go
- test/e2e/main.go
This updates the e2e test so that it doesn't make use of nigiri CLI since this is not installed in CI (we use a lighter version without installing the nigiri binary and CLI).
For this, the explorer interface has been updated so that an asset string argument is added to the Faucet method.
The amount type of this and also the Mint methods were source of mistakes in other tests, therefore they've changed from uint (sats) to float (BTC).
This closes #354.
This closes #345.
> Update explorer's Faucet,Mint methods & Make e2e test run in CI

- internal/core/application/trade_service.go
This adds a sanity check on the amount provided to the MarketPrice request, in order to make sure that it is big enough to calculate the expected counter-amount.
With this, all daemons that provide markets with fixed fees set will start rejecting requests in case their amounts are smaller than the respective fixed fee.
This closes #366.
BONUS: Prior this, the error returned when calculating the preview was incorrectly overwritten by the ErrServiceUnavailable one. Not anymore from now on.
> Fix preview of MarketPrice & fix error message

- .github/workflows/ci.yml
- cmd/tdex/config.go
- cmd/tdex/main.go
- cmd/tdexd/main.go
- config/config.go
- internal/core/application/blockchain_listener.go
- internal/interfaces/grpc/handler/trade.go
- internal/interfaces/grpc/macaroon_utils.go
- internal/interfaces/grpc/permissions/permissions.go
- internal/interfaces/grpc/service.go
This adds 2 new env vars TDEX_OPERATOR_EXTRA_IP and TDEX_OPERATOR_EXTRA_DOMAIN in order to add an IP address or a DNS domain to the Operator TLS certificate. This becomes useful when running dockerized daemons, or serving them as TOR hidden services.
The macaroons permissions have been modified in order to have more than just the operator and trade entities. Other entities have been added: _market_, _price_, _wallet_, _webhook_ and _unlocker_. This way, defining permissions becomes smoother and instead of defining permissions for each RPC method, it's possible to define actions for entities.
With this, 2 new macaroons `wallet.macaroon` and `webhook.macaroon` in addition to the others.
For what concerns the CLI, the hardcoded filenames for the macaroons file and the TLS certificate have …
> Add extraIP/extraDomain to Operator TLS cert & refactor macaroon permissons/files

- cmd/tdexd/main.go
- config/config.go
- internal/core/application/blockchain_listener.go
- internal/core/application/errors.go
- internal/core/application/operator_service.go
- internal/core/ports/pubsub.go
- internal/infrastructure/pubsub/webhook/service.go
- internal/infrastructure/pubsub/webhook/service_test.go
- internal/infrastructure/pubsub/webhook/webhook.go
- internal/interfaces/grpc/service.go
- test/e2e/main.go
This contains some little fixes to improve the behaviour of the daemon:
1. If using macaroon auth, now the TLS key is loaded from file or created depending whether it exists or not. The certificate is created if not existing. If Only the TLS cert exists in the datadir, an error is returned suggesting to delete it to create a new pair.
2. Market balance has been added to the payload of the outgoing request for the event ACCOUNT_WITHDRAW
3. Stop panicking in case of error. This improves the readability of error messages.
4. Minor: the definition of PubSub interface and related have been moved from _application_ to _ports_
This closes #376.
This closes #377.
This closes #378.
> Create or load TLS key + Add balance to ACCOUNT_WITHDRAW event payload

- cmd/tdexd/main.go
- config/config.go
- internal/interfaces/grpc/service.go
- pkg/wallet/transaction.go
- pkg/wallet/util.go
* With this, it is possible to provide multiple IPs or domains to the env vars `TDEX_OPERATOR_EXTRA_IP` and `TDEX_OPERATOR_EXTRA_DOMAIN` as strings of space separated elems. Example:
```
TDEX_OPERATOR_EXTRA_DOMAIN="my.provider.network my.provider.io" TDEX_OPERATOR_EXTRA_IP="" tdexd 
```
* A `DummyFeeAmount` has been introduced, used only for selecting unspents for paying network fees. Its value is set to `700` vB/sat.
After the coins have been selected, the real fee amount calculated from the tx size is returned, while the difference `DummyFeeAmoun - feeAmount` is added to the change.
This closes #384.
This closes #385.
> Rethink fee calculation in wallet.UpdateTx & Support multiple extra IPs/domains

- internal/core/application/trade_service.go
This prevents the daemon to panic when checking the validity of a trade proposal's price.
This closes #387.
> Hotfix: prevent panicking within isValidTradePrice

- internal/core/application/trade_service.go
- internal/core/domain/errors.go
- internal/core/domain/market_model.go
- internal/core/domain/market_service.go
- internal/core/domain/market_service_test.go
- internal/core/domain/pluggable_strategy.go
- pkg/marketmaking/formula/balanced_reserves.go
- pkg/marketmaking/formula/balanced_reserves_test.go
- pkg/marketmaking/market_making.go
This moves the whole price preview logic to the domain level, with the purpose to abstract the handling of a preview based on the market strategy at with a simple `market.Preview()` invocation at application level.
With this, a new `PluggableStrategy` data type is defined along with its method to make it compliant with the `mm.MakingFormula` interface.
The methods InGivenOut and OutGivenIn of the interface just mentioned have been slightly changed so that they accept opts of any type by expecting `interface{}`. It is then responsibility of the implementation to make sure that the opts are of the correct type by checking whether the interface casting succeeds or not.
Within the _balanced_ AMM formulas, the usage of the ChargeFeesOnThe WayIn has been fixed: before this that bool was …
> Move preview to domain level

- cmd/tdexd/main.go
- config/config.go
- internal/core/application/blockchain_listener.go
- internal/core/application/wallet_service.go
- internal/infrastructure/pubsub/webhook/service.go
- pkg/circuitbreaker/circuitbreaker.go
- pkg/crawler/crawler.go
- pkg/crawler/observable.go
- pkg/crawler/service.go
- pkg/crawler/service_test.go
This adds the circuit breaker strategy to the crawler's `Observable` components in order to retry failing network calls instead of returning error immediately in case any occur.
Closes #380.
> Add circuit breaker to observables

- .goreleaser.yml
- cmd/unlockerd/fileprovider.go
This makes the unlocker's file provider smart enough to trim leading and ending spaces or EOL (`\n`) when reading the password from file.
This also enhances the goreleaser YAML file by unifying the 2 unlocker's builds in one single entry.
Please @tiero review this.
> [Unlockerd] Trim spaces and EOL in file provider & unify goreleaser unlocker builds

- Dockerfile
This adds a user `user` to the debian image used for tdexd in order to prevent [cutomizing&hardcoding](https://github.com/TDex-network/tdex-daemon/blob/master/Dockerfile#L35) the daemon's datadir in a path different from the default one (in the appdata folder).
The previous image was also problematic for other binaries (tdex and unlockerd) whose defaulted to daemon's datadir `/root/.tdex-daemon` instead of the correct one `$HOME/.tdex-daemon`. This is now fixed and nor the CLI, nor the unlocker embedded in the image require to explicitly set tls/macaroons paths.
This closes #400.
> Fix docker container daemon datadir

- cmd/tdex/config.go
- cmd/tdex/main.go
This makes the previously mandatory step `config init [--network, ...]` optional.
Now, when the `getState` function is in charge of creating a state.json file with all default values in case it doesn't exist instead of returning an error that mentions to run `config init`.
This closes #341.
> [CLI] Auto create state file if not existing

- cmd/tdex/main.go
- pkg/macaroons/auth.go
Before this, the requirements for transport security of macaroons' credential was hardcoded (`true` value).
This, instead, makes it possible to disable TLS at will.
This closes #405 
> [pkg(macaroons] Allow disabling TLS

- cmd/tdexd/main.go
- internal/core/application/errors.go
- internal/core/application/operator_service.go
- internal/core/application/pubsub_utils.go
- internal/core/application/repo_utils.go
- internal/core/application/trade_service.go
- internal/core/application/trade_service_test.go
- internal/core/application/walletunlocker_service.go
Before this, the daemon wasn't "watching" for fee/market balances anymore (it used to do that with the help of the blockchain listener for versions prior to v0.3.0).
This makes the daemon checking balances whenever a trade proposal is handled or a market withdrawal is performed and the check is made over the balances including also locked unspents.
The fee account is in "low balance state" when the sum of its unspents' amount is equal or below the configurable FeeBalanceThreshold, while for a market it means that its base or quote balances are equal or below the respective fixed fee. In case the market fixed fee is not set, then the balance is low if one or both of them are equal to 0.
It's important to note that these checks are deferred: this means that for the fee account, even if its …
> Check fee/market low balances & publish topic on pubsub

- cmd/tdexd/main.go
- config/config.go
- internal/core/application/blockchain_listener.go
- internal/core/application/wallet_service.go
- internal/core/application/walletunlocker_service_test.go
This adds option to set lbtc asset hash of the network struct in regtest for the reasons explained in the issue itself.
It also removes unused marketBaseAsset property from blockchain_listener, wallet_service, walletunlocker_service.
This closes #408 
> native asset

- go.mod
- go.sum
- internal/core/application/operator_service.go
- internal/core/application/types.go
- internal/core/application/walletunlocker_service.go
- internal/core/domain/vault_model.go
- internal/infrastructure/storage/db/badger/db_manager.go
- internal/infrastructure/storage/db/badger/trade_repository_impl.go
- pkg/explorer/elements/unspents.go
- pkg/wallet/util.go
With this, the daemon will persist in a physical file into the datadir the entries of the unspent repository. For backward compatibility, at start time, if a wallet is found in the db, then if there are no unspents the daemon attempts to restore them like it was doing before this PR. Alternatively, it just signals that it is already restored and skip the process above.
This also fixes ALL slice initializations that were using assignment instead of concatenation.
This closes #411.
This closes #414.
> Persist unspents

- go.mod
- go.sum
- internal/core/application/wallet_service.go
This updates private method sendToMany so that it uses BlindTransactionWithData instead BlindTransactionWithKeys since stored unspents dont holds proofs info(tnx @altafan for the advise)
It fixes issue with Withdraw bug endpoint.
This closes #409 
>  WithdrawMarket RPC: use BlindTransactionWithData in sendToMany

- cmd/tdex/fragmentfee.go
- cmd/tdex/fragmentmarket.go
This adds new features to the fragmenter tool: both `fragmentfee` and `fragmentmarket` cmds now have 2 new flags defined:
* `--recover_funds_to_address` which lets the user passing an address where to eventually send all the funds stuck into the fragmented single-key wallet.
* `--debug` for debugging purposes, let the command print the hex of the transaction if it fails to be broadcasted.
Only for the `fragmentfee` command, this adds one more flag `--max_fragments` to override the max number of fragments that will eventually become deposits for the fee account.
Note that the previous `MaxNumOfOutputs` contact has been decreased from `150` to `50`.
Last but not least, this replaces the creation of slices via assignment with the use of `append` in the CLI commands.
Closes #437.
Please …
> Fix fragmenter

- pkg/wallet/keys.go
This fixes a not-yet tracked bug that was residing in pkg/wallet: the extended keys returned by both `ExtendedPrivateKey()` and  `ExtendedPublicKey()` were not the correct one because the account index provided as arg wasn't hardened in HD derivation.
> Hotfix: derivation of extended keys

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- internal/core/application/blockchain_listener.go
- internal/core/application/operator_service.go
- internal/core/application/trade_service.go
- internal/core/domain/trade_service.go
- internal/core/domain/trade_service_test.go
- internal/core/domain/unspent_repository.go
- internal/infrastructure/storage/db/badger/unspent_repository_impl.go
- internal/infrastructure/storage/db/inmemory/unspent_memory_repository_impl.go
- internal/infrastructure/storage/db/test/unspent_repository_impl_test.go
This fixes the badger implementation of the unspent repository so that it doesn't make use of badgerhold's methods like `Get()` or `Update()` to read/write data from/to the store. They are replaced by `Find()` and `UpdateMatching()` that actually query the store instead of getting/updating an elem by its key.
There is still an [open issue](https://github.com/timshannon/badgerhold/issues/76) on the badgerhold repo for this. These changes could eventually be rolled back if we figure out the reason of such weird misbehavior.
This closes #452.
BONUS:
- This fixes the trade domain to prevent being able to settle a trade if it's failed (a dedicated test case has been added to prove it)
- This fixes the bc listener to properly stop the outpoint observation if the transaction has failed for any …
> Bader DB: Use Find() and UpdateMatching() 

- internal/interfaces/grpc/permissions/permissions.go
This updates the name of the RPCs and also adds those missing to the list of macaroons permissions.
This also fixes the entities associated for each permission.
Please @tiero  review this.
> Hotfix: Update name of RPCs for macaroons permissions

- internal/core/application/trade_service.go
- internal/core/application/trade_service_test.go
- internal/core/application/walletunlocker_service_test.go
- internal/interfaces/grpc/handler/trade.go
- pkg/crawler/service_test.go
This adds a mutex on the TradePropose RPC in order to grant reclusive access to the method, preventing the daemon from attempting to double spend its UTXOs in case of "concurrent" proposals, ie. incoming requests nearly at the same time.
Because of this, the parallelization of the tests has been restored to prove that now the daemon can handle this eventuality.
Minor fixes:
* Do not use pointer to interfaces in TradeComplete
* Fixes failing test in TestInitWallet
* Do not log events in TestCralwerService but check that events are actually received
Closes #388.
> Lock on propose

- internal/interfaces/grpc/permissions/permissions.go
This makes the Operaror/ListMarket rpc accessible by the price entity and all those extending it.
Closes #480.
> Update price.macaroon permissions

- internal/core/application/errors.go
> Fix typo in ErrWithdrawAmountTooBig error message

- cmd/tdexd/main.go
- config/config.go
- internal/core/application/trade_service.go
- internal/core/application/trade_service_test.go
- internal/core/application/types.go
This adds a new env var `TDEXD_TRADE_SATS_PER_BYTE` that allows to configure the ratio sat/byte to use when paying for network fees of accepted trades.
Closes #463.
> Add configurable sats/byte for trade interface

- .github/workflows/release.yml
- .goreleaser.yml
- Dockerfile
- cmd/tdex/config.go
- cmd/tdex/main.go
- Remove `explorer` package from `tdex` cli, since is not used and this let us build the cli without CGO
- GoReleaser: Add a specific build step for `linux-arm64` and `darwin-arm64`
- Install Linux packages system wide `aarch64-linux-gnu-gcc` & `aarch64-linux-gnu-g++` needed to cross compile linux arm64
- referenced `o64-clang` & `oa64-clang++`  from OSX targets to build for new Apple Silicon chips
- GoReleaser: build two separated docker images for each architecture (arm,amd64) and merge them via `docker_manifests`
It closes #483
> GoReleaser: pre-compile linux & darwin arm64 binaries & docker images

- internal/interfaces/grpc/permissions/permissions.go
This adds the (missing) entries for fee and market fragmenter RPCs to the list of macaroons permissions.
Closes #488.
> Add permissions for fragmenter RPCs

- cmd/tdexd/main.go
- config/config.go
- internal/core/application/blockchain_listener.go
- internal/core/application/operator_service.go
- internal/core/application/operator_service_test.go
- internal/core/application/trade_service.go
- internal/core/application/trade_service_test.go
- internal/core/application/types.go
- internal/core/application/wallet_service.go
- internal/core/application/walletunlocker_service.go
- internal/core/application/walletunlocker_service_test.go
- internal/core/domain/market_repository.go
- internal/core/domain/trade_model.go
- internal/core/domain/trade_service.go
- internal/core/domain/trade_service_test.go
- internal/infrastructure/storage/db/badger/market_repository_impl.go
- internal/infrastructure/storage/db/inmemory/db_manager.go
- internal/infrastructure/storage/db/inmemory/market_memory_repository_impl.go
- internal/infrastructure/storage/db/test/market_repository_impl_test.go
- test/e2e/main.go
This adds a new env var `TDEX_QUOTE_ASSET` to allow the user to fix the quote asset of the markets it will then open instead of the base one.
Internally, this means that the quote asset is not an always-changing value anymore because it could be fixed. Therefore, it cannot be used alone to identify a market but must be used together with the base asset to find a market domain in the repo.
This requires to change the market repository method `GetMarketByAsset(context, marketQuoteAsset)` to `GetMarketByAssets(context, marketBaseAsset, marketQuoteAsset)`.
Always for the same reason, it is now required that the trade domain stores not only the mkt quote asset, but also the base one.
This also enforces at application level that the base/quote assets of the market provided by the user in …
> Add TDEX_QUOTE_ASSET env var & Enforce asset pair of NewMarket request to match the one fixed by the daemon

- internal/core/domain/errors.go
- internal/core/domain/market_service.go
- internal/core/domain/market_service_test.go
- internal/core/domain/pluggable_strategy.go
- internal/infrastructure/storage/db/badger/market_repository_impl.go
- pkg/marketmaking/market_making.go
This introduces changes to fix the strategy type returned by the daemon and to not require both the base and the quote fee to be defined to update the market fixed fee.
Closes #500.
Cloeses #501.
> Fix pluggable strategy type & Allow only base/quote fixed fee when updating

- api-spec/protobuf/gen/operator/operator.pb.go
- api-spec/protobuf/gen/operator/operator_grpc.pb.go
- api-spec/protobuf/operator.proto
- cmd/tdex/config.go
- cmd/tdex/market.go
- cmd/tdexdconnect/main.go
- config/config.go
- go.mod
- go.sum
- internal/core/application/errors.go
- internal/core/application/operator_service.go
- internal/core/application/operator_service_test.go
- internal/interfaces/grpc/handler/operator.go
- internal/interfaces/grpc/http_utils.go
* Introduces check to be sure that a market has 0 balance before dropping. Closes #505.
* Adds support for testnet. Closes #506.
* Adds a new GetMarketInfo RPC to retrieve info of a single market. Closes #498.
* [tdexdconnect] Allows to specify either a IP address or a DNS name for flag `--rpcserver`.
> Support Testnet && Add GetMarketInfo && Do not DropMarket with funds && [tdexdconnect] support DNS names in --rpcserver 

- internal/core/application/explorer_utils.go
- internal/core/application/mocks_test.go
- internal/core/application/operator_service.go
- pkg/crawler/mock_test.go
- pkg/explorer/elements/transaction.go
- pkg/explorer/esplora/transaction.go
- pkg/explorer/explorer.go
This adds a waiting function that polls the explorer until the fee/market funding transaction made with the related fragmenter is returned.
Only after this, the fragmenter can proceed with claiming the funds for the account.
Closes #514.
Closes #517.
~~EDIT: This adds also a check to prevent splitting too small amounts in fee fragmentation~~
> Fragmenters: Wait for tx to be returned by the explorer before claiming & Use fee account to cover fees of market fragmentation

- internal/interfaces/grpc/permissions/permissions.go
This fixes the macaroon permission for the GetMarketInfo RPC.
> Hotfix GetMarketInfo macaroon permission

- cmd/tdex/market.go
- internal/core/application/constants.go
- internal/core/application/operator_service.go
- internal/core/domain/errors.go
- internal/core/domain/market_service.go
- internal/core/domain/market_service_test.go
- internal/interfaces/grpc/permissions/permissions.go
- internal/interfaces/grpc/permissions/permissions_test.go
Before this, every market fragmentation required to send both assets to the fragmenter account. Now, this behavior is maintained only in case the market has zero balance, otherwise the operator is allowed to fragment funds of only one asset of the pair.
- Closes #522.
- closes #521 by using the special `-1` value to ignore change to base/quote fee instead of using `0`.
- closes #525 by using `localhost:5001` for regtest instead of `localhost:3001`
- closes #523 and added a test to make sure that all methods are either whitelisted or restricted by a permission
- closes #504 by updating the error messages as requested
> Allow fragmenting only one asset of the pair for already funded markets

- pkg/wallet/util.go
This fixes the bug that makes the daemon crash when serving trades with a counter-part using multisig scripts.
Closes #541.
> Hotfix: prevent daemon crashing when calculating trade fees

- go.mod
- go.sum
- internal/interfaces/grpc/handler/trade.go
- internal/interfaces/grpc/handler/trade_old.go
- internal/interfaces/grpc/permissions/permissions.go
- internal/interfaces/grpc/permissions/permissions_test.go
- internal/interfaces/grpc/service.go
This adds support for the old version of tdex-protobuf (before migrating to buf):
- adds a new grpc tradeOldHandler using the same application service, but depending on tdex-protobuf#master instead of #v1 
- adds registration of the handler above to the trade grpc server
- adds macaroon permissions to whitelist accordingly
NOTE: the old version of tdex-protobuf does not have support for grpc-gateway, therefore that part has not been affected by changes.
Closes #583.
> Add backward compatibility with old version of tdex-protobuf

- .goreleaser.yml
- internal/interfaces/grpc/service.go
This fixes the connection established by the trade grpc gateway to the grpc server, by adding a `InsecureSkipVerify: true` to the tls configuration.
Closes #598.
> [Hotfix] Make trade HTTP JSON interface reachable

- cmd/tdexd/main.go
- internal/core/application/trade_service.go
- internal/core/application/trade_service_test.go
- internal/core/application/types.go
- internal/infrastructure/storage/db/badger/trade_repository_impl.go
- internal/interfaces/grpc/service.go
This makes the trade service restore the watch for accepted trades and locked utxos.
NOTE: if a trade is already expired, the service doesn't update it's status immediately and releases the lock of the utxos, but it waits for a minute before doing that. This to give the time to the bc listener to eventually be notified about a settled trade so that it can correctly update its status and spend the utxos instead.
Closes #564.
> Restore watch for trades and unspents after restart

- .goreleaser.yml
- goreleaser.Dockerfile
This updates goreleaser config so that build info's are injected in binaries.
This closes #592
> Goreleaser build info fix

- api-spec/protobuf/tdex-daemon/v1/operator.proto
Using https://github.com/timostamm/protobuf-ts, the default option for message fields with 64 bit integral values is `[jstype = JS_NORMAL]` / BigInt.
Add [jstype = JS_NUMBER] option to small numbers to override the default.
Please review @tiero
> Set [jstype = JS_NUMBER] option to small numbers

- cmd/tdex/config.go
- cmd/tdex/main.go
- cmd/tdexd/main.go
- config/config.go
- internal/interfaces/grpc/service.go
- internal/interfaces/grpc/service_one_port.go
This adds option to run daemon without operator TLS and macaroon ON.
This adds self-signed TLS cert to the single port server setup.
This closes #620 
This closes #614 
> No operator tls & Single port cert

- Makefile
- cmd/tdex/config.go
- cmd/tdex/main.go
- config/config.go
- internal/interfaces/grpc/service.go
- internal/interfaces/grpc/service_one_port.go
Before this, TLS enabled/disabled for operator interface still depended on `NO_MACAROONS` env var, therefore it wasn't impossible to run a daemon with TLS enabled and macaroons disabled for that interface.
With this TLS auth depends only on `NO_OPERATOR_TLS` env var, therefore it is possible to enable and disable both tls and macaroons at will for operator interface.
This also renames the CLI flag `--no_operator_tls` to `--no_tls`. It's meant to be used to interact with the operator interface only, therefore we can simplify the naming of the flag.
> Decouple tls and macaroons auth

- internal/interfaces/http/tdex_connect_handler.go
- pkg/wallet/cypher.go
StatusUnauthorized 401 error response should always have a specific "WWW-Authenticate" header https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/WWW-Authenticate
This adds the missing header to the response of `/tdexdconnect` endpoint.
Furthermore, this changes the way the password passed to `/tdexdconnect` is validated: we now compare the password hashes rather than doing an actual decryption which is expensive in terms of resources and waiting time.
BONUS: this fixes eventual resource glitches after calling `Encrypt | Decrypt` functions from `pkg/wallet`.
Please @tiero @Janaka-Steph review this.
> Add missing header to /tdexdconnect response & Fix password validation

- internal/core/application/operator_service_test.go
- internal/core/application/types.go
- internal/interfaces/grpc/handler/operator.go
This fixes bug that was happening when GetMarketReport RPC was invoked with predefined period PREDEFINED_PERIOD_ALL.
This closes #605 
@tiero @altafan @Janaka-Steph please review.
> Fix GetMarketReport predefined period all

- internal/interfaces/grpc/http_utils.go
This unsets isCA certificate indicator.
Regarding: "We might want to explore also if it's possible to remove its expiration date. Currently, it is set to [1 year](https://github.com/tdex-network/tdex-daemon/blob/master/internal/interfaces/grpc/http_utils.go#L70)" -> I dont see any validation preventing this.
This closes #645 
> TLS unset isCA indicator

- web/layout.html
If someone is exposing the daemon with some reverse proxy on ie. `/api` the web page would not have worked calling the `/tdexdconnect` endpoint on the main host not honoring base pathname
> add pathname to increase supports of all deployments

- internal/core/application/trade_service.go
- internal/core/domain/market_model.go
- internal/core/domain/market_service.go
- internal/core/domain/market_service_test.go
- internal/core/domain/pluggable_strategy.go
- pkg/marketmaking/formula/balanced_reserves.go
- pkg/marketmaking/formula/balanced_reserves_test.go
- pkg/marketmaking/market_making.go
This updates the marketmaking Formula interface in order to express numbers via `decimal.Decimal`s instead of `uint64`s.
Before this change the the formula interface was designed to support satoshis, but this becomes problematic after supporting market assets precision. By changing the representation to `decimal.Decimal`, balances and amounts can be scaled by asset precision before and after applying a formula to calculate a preview amount (in domain layer).
This adds test cases to make sure the applied change work as expected.
This also simplify the calc of the min tradable amount of SpotPrice by applying the following formula:
```
mkt.FixedFee.BaseFee > 0 -> minTradableAmount = mkt.FixedFee.BaseFee+1
mkt.SpotPrice.BasePrice >= 1 -> minTradableAmount = 1
mkt.SpotPrice.BasePrice < 0 > …
```
> Fix preview amounts after supporting precisions

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e.yml
This updates the gh actions by adding the newly created `v1` to the list of target branches along with `master`.
> Update gh actions
